### ISSUE TITLE
Issue app download

### ISSUE THREAD

**Issue by amro1435** [skyguy126/Xposed-SoundCloudDownloader#1]
The app can't be downloaded.

**Comment by skyguy126** [comment]
@amro1435 I assume you mean from the xposed installer, it works fine for me. Could you provide a few more details regarding your issue?

**Comment by amro1435** [comment]
Every time I try to download the module it shows error 404 and when i try to download it from the website directly it shows"page not found,  The requested page "/xposed/files/modules/com.skyguy126.soundclouddownloader_v1_050ef5.apk" could not be found.
P.S.
If you need some screenshots tell me any way to send them to you.

**Comment by skyguy126** [comment]
@amro1435 I think it may be my fault, I accidently double clicked the button when adding it to the Xposed repository and it may have glitched the system. I already emailed them, just waiting for a response at this point. In the meantime try downloading it from here (github releases, same apk) https://github.com/skyguy126/Xposed-SoundCloudDownloader/releases  and let me know if it works.

**Comment by amro1435** [comment]
I've tried now to it from the link you sent and it works flawlessly..!!
Thank you a lot..!!

**Comment by skyguy126** [comment]
Glad to hear! I hope to have the repository issue sorted out soon.

**Comment by skyguy126** [comment]
@amro1435 I tried something with the Xposed Repository, could you try downloading it from the xposed installer and tell me if it works, please. Thanks!

**Comment by amro1435** [comment]
I've​ tried now and it still showing the same error (error 404);when i try to download from the app of xposed.
So I've tried to access to the repository page but now it shows this:
Access denied
You are not authorized to access this page.

**Comment by skyguy126** [comment]
@amro1435 thanks for the info, i guess ill just have to wait and see.

**Comment by amro1435** [comment]
You're welcome @skyguy126

**Comment by amro1435** [comment]
@skyguy126 I've tried to download it now and it has been downloaded successfully..!!

**Comment by skyguy126** [comment]
Removed and reuploaded it, everything should work fine now.
