### ISSUE TITLE
suggestion [adding cover artwork +id3 tags to the mp3 file ]

### ISSUE THREAD

**Issue by waelchateur** [skyguy126/Xposed-SoundCloudDownloader#11]
can u please add auto id3 tags and artwork feature to ur project

**Comment by skyguy126** [comment]
this might be a delayed feature, I'm trying to find a nice library for mp3 tags.

**Comment by waelchateur** [comment]
https://sites.google.com/site/eternalsandbox/myid3-for-android

**Comment by waelchateur** [comment]
take a look at that maybe will help

**Comment by waelchateur** [comment]
https://github.com/mpatric/mp3agic

**Comment by skyguy126** [comment]
That was the first one I tried actually. It doesn't compile in android for some reason. I think its due to how it needs java 1.8 to run.

**Comment by waelchateur** [comment]
did u see this 
https://github.com/hexise/jaudiotagger-android

**Comment by master801** [comment]
@skyguy126 Why do you want to avoid using Java 8? Is it for backwards-compatibility in Android?

**Comment by skyguy126** [comment]
Android only supports a small subset of features in java 8. The ones required by the library are not and this leads to compilation failure.

**Comment by skyguy126** [comment]
For some reason I can't seem to compile the jaudiotagger library, I'm getting maven build errors. Can anyone point me towards figuring out how to compile it or perhaps finding another library?

**Comment by skyguy126** [comment]
Update: Found a tagging library and everything is working well so far. Code needs to be refactored and a few things need to be stabilized still.

**Comment by skyguy126** [comment]
Added with c47bed25cee45be5b7f4346d285951f051ba0500. Will require more testing before release.

**Comment by waelchateur** [comment]
Just wow 😍 well done bro its works flawlessly .... i was waiting for something like this thank you and good luck on your projects ...... thanks a lot 👌
