### ISSUE TITLE
No longer see download button

### ISSUE THREAD

**Issue by kgptzac** [skyguy126/Xposed-SoundCloudDownloader#12]
i noticed after SoundCloud 2018.02.14 update I can no longer see the download button as before.
[xposed_error_20180214_132954.log](https://github.com/skyguy126/Xposed-SoundCloudDownloader/files/1725385/xposed_error_20180214_132954.log)

**Comment by skyguy126** [comment]
Will need to update the hooks for the new version.

**Comment by gdimakis** [comment]
Same issue here!
Waiting For Update.

**Comment by skyguy126** [comment]
there seems to be pretty drastic changes to the code, looking like the module needs a rewrite

**Comment by Jeffdow85** [comment]
That sounds time consuming for you the developer. Think I'll downgrade to last version lol. Thanks for your work. Great modual!

**Comment by skyguy126** [comment]
Fixed with d85341fa8a53b4e8c92366dc3556c4bc6613cdcc.

**Comment by gdimakis** [comment]
Fixed so soon!!!
Thank you very much!!
