### ISSUE TITLE
Not downloading some tracks

### ISSUE THREAD

**Issue by FahadYousafMahar** [skyguy126/Xposed-SoundCloudDownloader#15]
I am new to modding and i recently installed this downloader . 
It's great and i thank you for making our lives a lot easier. It's working great on most tracks. But there are some tracks on which download button is not working (Pressing the button does nothing ).
I don't know if there is a premium policy of SoundCloud that blocks downloads or what it is. But it's strange that it works on most tracks and doesn't on some. I tried to download tracks of ' CokeStudio ' and button didn't start download.

Thanks in advance.

**Comment by FahadYousafMahar** [comment]
I am using samaung j510f with xposed v87.1 Marshmallow 6.0.1 and scd 1.5.1 with soundcloud 14.2.18 release and my logs are empty.

**Comment by skyguy126** [comment]
There's been an update it seems, hooks need to be updated again.

**Comment by FahadYousafMahar** [comment]
Thanks for looking into it.

**Comment by waelchateur** [comment]
Download button disspear :
Xposed  (10385): [SoundCloud Downloader] Module entry, version 1.5.1
03-05 11:06:56.697 I/Xposed  (10385): [SoundCloud Downloader] Error: emx(avf,bkv)#exact
(Soundcloud 26/02/2018 realease)

**Comment by skyguy126** [comment]
Fixed with 4f1c4a2928719f9e1dc596b8df2dc2061562dd2c
