### ISSUE TITLE
can't use in 04-06 release verison

### ISSUE THREAD

**Issue by naloder** [skyguy126/Xposed-SoundCloudDownloader#19]

**Comment by steezmoso** [comment]
Also having this issue.  Uninstaller and reinstalled both apps but no resolution.

**Comment by skyguy126** [comment]
The module needs to be updated to match the new method signatures (this needs to happen every time sound cloud is updated). Unfortunately, I am becoming very busy with university as I get closer to the end of the school year and I don't think I'll be able to do further work on this module at-least for the time being (few weeks-months). If anyone is willing to step up and maintain this module in conjunction with me I'd much appreciate it; I can even show you how to go about the update process.

**Comment by FahadYousafMahar** [comment]
I would really like to help you in this matter. I am php developer and I have studied c++.
I am not familiar with Java.
Can I be of any use. If updating webhooks is a work which can be done without any Java experience then I am ready to do that.

**Comment by skyguy126** [comment]
@FahadYousafMahar Do you have android studio and the SDK installed. If not, go ahead and do that. I might be able to make a tutorial video or something to help you get started. Join this slack workspace and we can discuss further: https://join.slack.com/t/xposed-scd-dev/shared_invite/enQtMzQ4NDAzMTg5MjY3LWYyYTE5MGMyNTNiMDYzYzJmMzQzMDAyZWZlNjlhYWYwNjRmZTVlMGQ2MDBhOWQ1YjkxZGRiZmY2ZDQ0YmEzNmU

This goes for everyone else interested as well, thanks!

**Comment by skyguy126** [comment]
fixed with d6391fdf00f1e0a0acc6208ac1ebb98ec2d1d009
