### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by iammanpreetsachdeva** [skyguy126/Xposed-SoundCloudDownloader#2]
Showing error.. 404. Download failed. 
Device: OnePlus X
Root status: Ok
Battery: 36%

**Comment by skyguy126** [comment]
@iammanpreetsachdeva From #1; "I think it may be my fault, I accidently double clicked the button when adding it to the Xposed repository and it may have glitched the system. I already emailed them, just waiting for a response at this point. In the meantime try downloading it from here (github releases, same apk) https://github.com/skyguy126/Xposed-SoundCloudDownloader/releases and let me know if it works."
