### ISSUE TITLE
Download feature doesn't work

### ISSUE THREAD

**Issue by EgyBoy1** [skyguy126/Xposed-SoundCloudDownloader#20]
Greetings, 

I have installed the last version of your module, but when i try to download any track it appears on notification bar but doesn't progress. 

SoundCloud version on my device is 22.03.2018-release. 

I hope you can help me with this, thanks at advance.

**Comment by skyguy126** [comment]
Refer to #19.

**Comment by EgyBoy1** [comment]
Thanks, good luck with your study. 
 I hope i can help you, i have more time but don't have any programming experience.

**Comment by skyguy126** [comment]
thank you, I hope to get back on this project as soon as possible!
