### ISSUE TITLE
SoundCloud Downloader not show download option

### ISSUE THREAD

**Issue by Jhoscy** [skyguy126/Xposed-SoundCloudDownloader#22]
I Just installed the Module, but the SoundCloud app don't show (after click on the three menu options of the track) the Download option. I don't now if depends for SoundCloud version, or If because I have Oreo 8.1 (OP5T), or even more serious..I'm in Italy with Italian app (I know that more features are available in other country). Thanks in Advance!

**Comment by FahadYousafMahar** [comment]
it depends on sound cloud version. SCD is meant to be updated for every new
SoundCloud release but as developer is busy so there hasn't been a new one
around. Hands SCD doesn't work.
I hope someday the developer is about to share tutorials for how to update
it

**Comment by Jhoscy** [comment]
Thank You man for immediately reply!  I understand the motivations. I'm waiting yours next steps..

**Comment by skyguy126** [comment]
I hope to be able to get back on this, not sure what the user base is like now but I'll try for the near future. working full time atm so its a bit tough

**Comment by Jhoscy** [comment]
Okk man I appreciate your work and I don't know if someone pays for this, so thanks! The problem in Italy is that the SoundCloud Go (premium) is not available. You know happen to listen to music while offline, and the SoundCloud's track for the most parte aren't on Spotify ecc..so this was a middle way. Good work!!

**Comment by skyguy126** [comment]
fixed with d6391fdf00f1e0a0acc6208ac1ebb98ec2d1d009 :)

**Comment by Jhoscy** [comment]
Thanks so much man, It works very fine, just tested!  Respect from Italy!! 😊
