### ISSUE TITLE
Latest SoundCloud update - Broken

### ISSUE THREAD

**Issue by QuickOK** [skyguy126/Xposed-SoundCloudDownloader#24]
Latest SoundCloud update appears to have broken the SoundCloud Downloader. Download button no longer appears under "three dots".

**Comment by skyguy126** [comment]
could you post the xposed log, scd version and soundcloud version.
thanks

**Comment by QuickOK** [comment]
2018.07.02-release is SoundCloud version. 1.5.5 is installed Xposed module version

**Comment by skyguy126** [comment]
can you post the xposed log?

**Comment by QuickOK** [comment]
Dunno how you want the log posted. Haven't done this in awhile

**Comment by skyguy126** [comment]
copy paste is fine

**Comment by QuickOK** [comment]
07-03 00:59:14.718 I/Xposed  (  755): -----------------
07-03 00:59:14.718 I/Xposed  (  755): Starting Xposed version 90.2-beta3 (Systemless), compiled for SDK 27
07-03 00:59:14.718 I/Xposed  (  755): Device: Pixel 2 XL (Google), Android version 8.1.0 (SDK 27)
07-03 00:59:14.718 I/Xposed  (  755): ROM: OPM4.171019.021.E1
07-03 00:59:14.718 I/Xposed  (  755): Build fingerprint: google/taimen/taimen:8.1.0/OPM4.171019.021.E1/4769646:user/release-keys
07-03 00:59:14.718 I/Xposed  (  755): Platform: arm64-v8a, 64-bit binary, system server: yes
07-03 00:59:14.718 I/Xposed  (  755): SELinux enabled: yes, enforcing: yes
07-03 00:59:14.757 I/Xposed  (  755): -----------------
07-03 00:59:14.757 I/Xposed  (  755): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
07-03 00:59:16.104 I/Xposed  (  755): Detected ART runtime
07-03 00:59:16.106 I/Xposed  (  755): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
07-03 00:59:16.298 I/Xposed  (  755): Loading modules from /data/app/com.skyguy126.soundclouddownloader-Y_QSbleHngruTyANZUR8IA==/base.apk
07-03 00:59:16.432 I/Xposed  (  755):   Loading class com.skyguy126.soundclouddownloader.XposedMod
07-03 00:59:24.893 I/Xposed  (  756): -----------------
07-03 00:59:24.894 I/Xposed  (  756): Starting Xposed version 90.2-beta3 (Systemless), compiled for SDK 27
07-03 00:59:24.894 I/Xposed  (  756): Device: Pixel 2 XL (Google), Android version 8.1.0 (SDK 27)
07-03 00:59:24.894 I/Xposed  (  756): ROM: OPM4.171019.021.E1
07-03 00:59:24.894 I/Xposed  (  756): Build fingerprint: google/taimen/taimen:8.1.0/OPM4.171019.021.E1/4769646:user/release-keys
07-03 00:59:24.894 I/Xposed  (  756): Platform: arm64-v8a, 32-bit binary, system server: no
07-03 00:59:24.894 I/Xposed  (  756): SELinux enabled: yes, enforcing: yes
07-03 00:59:24.898 I/Xposed  (  756): -----------------
07-03 00:59:24.899 I/Xposed  (  756): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
07-03 00:59:25.727 I/Xposed  (  756): Detected ART runtime
07-03 00:59:25.729 I/Xposed  (  756): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
07-03 00:59:25.875 I/Xposed  (  756): Loading modules from /data/app/com.skyguy126.soundclouddownloader-Y_QSbleHngruTyANZUR8IA==/base.apk
07-03 00:59:25.968 I/Xposed  (  756):   Loading class com.skyguy126.soundclouddownloader.XposedMod
07-03 00:59:54.716 I/Xposed  ( 3598): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 00:59:54.738 I/Xposed  ( 3598): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 01:01:31.089 I/Xposed  ( 8309): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 01:01:31.107 I/Xposed  ( 8309): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 01:10:42.915 I/Xposed  (13355): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 01:10:42.941 I/Xposed  (13355): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 02:10:58.361 I/Xposed  (24158): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 02:10:58.387 I/Xposed  (24158): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 03:01:20.836 I/Xposed  (29147): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 03:01:20.864 I/Xposed  (29147): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 04:10:43.271 I/Xposed  ( 2134): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 04:10:43.295 I/Xposed  ( 2134): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 05:11:17.173 I/Xposed  (11761): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 05:11:17.206 I/Xposed  (11761): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 06:02:02.320 I/Xposed  (15490): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 06:02:02.333 I/Xposed  (15490): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 07:12:15.045 I/Xposed  (19464): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 07:12:15.052 I/Xposed  (19464): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 08:01:31.371 I/Xposed  (22285): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 08:01:31.378 I/Xposed  (22285): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 09:02:14.993 I/Xposed  (27152): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 09:02:14.998 I/Xposed  (27152): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 09:12:15.052 I/Xposed  (28091): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 09:12:15.057 I/Xposed  (28091): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 10:10:43.127 I/Xposed  ( 3481): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 10:10:43.139 I/Xposed  ( 3481): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 10:51:26.512 I/XposedInstaller( 8269): Downloaded http://dl.xposed.info/repo/partial/15271.xml.gz with status 0 (error: null), size 66 bytes
07-03 10:51:26.514 I/XposedInstaller( 8269): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 15271 (0 new / 0 removed modules)
07-03 10:51:27.839 I/XposedInstaller( 8269): Downloaded http://dl.xposed.info/repo/partial/15271.xml.gz with status 0 (error: null), size 66 bytes
07-03 10:51:27.840 I/XposedInstaller( 8269): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 15271 (0 new / 0 removed modules)
07-03 10:55:22.563 I/Xposed  ( 8792): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 10:55:22.576 I/Xposed  ( 8792): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact
07-03 11:48:08.662 I/Xposed  (13555): [SoundCloud Downloader] Module entry, version 1.5.5
07-03 11:48:08.684 I/Xposed  (13555): [SoundCloud Downloader] Error: fgk(bmx,cfa)#exact

**Comment by ijolkowboi** [comment]
Not working for me either. There is no download button.

**Comment by skyguy126** [comment]
Yeah it needs to be updated for the new version :/. Will try sometime soon hopefully

**Comment by QuickOK** [comment]
Is this something SoundCloud is trying to combat or is this something the SoundCloud changed and it just happened to break the Sound Cloud Downloader?

**Comment by skyguy126** [comment]
Hard to tell. I believe they switched over to Kotlin and all the code in the apk is generated by a tool that compiles kotlin. Every time they make a change (which happens around every 2-4 weeks) some of the variable and class names get changed which breaks scd. The code is essentially obfuscated which makes it slightly annoying but as of right now it should still be doable.

**Comment by skyguy126** [comment]
fixed with 7fde7bbdacae5ca898b026c81b70da7fa7c1f7ef :).
