### ISSUE TITLE
new Soundcloud release

### ISSUE THREAD

**Issue by ghost** [skyguy126/Xposed-SoundCloudDownloader#25]
again update broke downloader :(

**Comment by waelchateur** [comment]
@tomimarcincin its working fine for me there is no essue

**Comment by skyguy126** [comment]
can confirm it is broken :(. They update very often now it seems. I'd suggest just using the old version till hooks get updated unfortunately.

**Comment by QuickOK** [comment]
I'm going to have to start using titanium backup for each SoundCloud update. To regress to the old version.

**Comment by waelchateur** [comment]
@quickok you can get the old builds from  apkmirror no need to backup

**Comment by QuickOK** [comment]
Thanks

**Comment by yourbestregard** [comment]
which version should I use?
I have tried all the versions, but nothing works. https://ibb.co/kveH48

**Comment by QuickOK** [comment]
I tried regressing to the July version, but as we've found out that doesn't
work. Any ideas?

**Comment by skyguy126** [comment]
release 2018.07.02

**Comment by QuickOK** [comment]
Thanks. I should note that the current soundcloud version (whatever version
it may be) must be uninstalled first, before the previous version is
installed (which I didn't try before posting my last message). Works so
far. Thanks.

**Comment by the-real-jb** [comment]
Can also use installerOps, downgrade feature

**Comment by waelchateur** [comment]
@gametimebrizzle 
this feature is only for system apps not for user apps only if you mange to move soundcloud to system

**Comment by skyguy126** [comment]
fixed with db356f9bf65dc7b7194a79374edf5bda6bb786c3
