### ISSUE TITLE
Artwork essue when adding metadata

### ISSUE THREAD

**Issue by waelchateur** [skyguy126/Xposed-SoundCloudDownloader#26]
@skyguy126 first i wanna thank you for this fabulous module and thank you for keeping updating hook method.
overall the module is working fine the only thing i see is the low quality artwork  that is added to the metadata 
and there is a 2nd essue that sometimes artwork not added to metadata ..
in mean time i have a solution for it i use another app that search artwork and its perfect its called automatag....
maybe i have an idea tha can help you fix the essue there is a javascript that can grab HD artwork from soundcloud 
i dont know if his main idea can be applied to the hook method

**Comment by waelchateur** [comment]
https://greasyfork.org/en/scripts/14591-soundcloud-album-art-downloader/code
take a look @skyguy126

**Comment by waelchateur** [comment]
i guess i found out why artwork always  being downloaded in low quality 
in downloadcatcher.java i see that the app is injecting only 250/250px 
i dont know  if this is the real cause 
and i see the bitmap jpeg compressor is at 90% in metadatainjector.java 
maybe you have done this to make all the processe more faster but this is a little annoying

so my suggestion is that can we get the original artwork 500/500 pls 
or it can be an option to select the quality of artwork  (original / medium / low )
and thank you

**Comment by skyguy126** [comment]
Artwork should be added to metadata every time, can you post your Xposed log here so I can check for errors. I just set it at 250x250 and 90% because that seemed to give the best quality at the smallest file size. Adding a setting was on my todo list but never got around to it.

@stirante If you possibly have a little bit of free time could you take a look at this, otherwise its fine.

**Comment by waelchateur** [comment]
i have tryed to modify the bitmap compression ratio to 100%
0% didnt worked for me the artwork looks agly
and i changed "t250/250" by "original" so i can got the original size of the artwok 
it works perfectly

this is the log you demanded :

07-12 01:04:23.246 I/Xposed  ( 9508): [SoundCloud Downloader] Module entry, version 1.5.6
07-12 01:04:23.290 I/Xposed  ( 9508): [SoundCloud Downloader] Initialized
07-12 01:04:31.620 I/Xposed  ( 9508): [SoundCloud Downloader] Entered download catcher...
07-12 01:04:31.626 I/Xposed  ( 9508): [SoundCloud Downloader] Track name: VSNS - Wild Love
07-12 01:04:31.630 I/Xposed  ( 9508): [SoundCloud Downloader] Found genre data...
07-12 01:04:31.630 I/Xposed  ( 9508): [SoundCloud Downloader] Image url: https://i1.sndcdn.com/artworks-000338624265-qig8ss-original.jpg
07-12 01:04:31.640 I/Xposed  ( 9508): [SoundCloud Downloader] com.skyguy126.soundclouddownloader scd_prefs
07-12 01:04:31.643 I/Xposed  ( 9508): [SoundCloud Downloader] Include metadata: true
07-12 01:04:31.643 I/Xposed  ( 9508): [SoundCloud Downloader] Save location: 1
07-12 01:04:31.646 I/Xposed  ( 9508): [SoundCloud Downloader] Download path: /storage/emulated/0/Download/VSNS - Wild Love.mp3
07-12 01:04:31.650 I/Xposed  ( 9508): [SoundCloud Downloader] Adding metadata injector...
07-12 01:04:50.713 I/Xposed  ( 9508): [SoundCloud Downloader] Entered download catcher...
07-12 01:04:50.713 I/Xposed  ( 9508): [SoundCloud Downloader] Track name: VSNS - Wild Love
07-12 01:04:50.713 I/Xposed  ( 9508): [SoundCloud Downloader] Found genre data...
07-12 01:04:50.713 I/Xposed  ( 9508): [SoundCloud Downloader] Image url: https://i1.sndcdn.com/artworks-000338624265-qig8ss-original.jpg
07-12 01:04:50.723 I/Xposed  ( 9508): [SoundCloud Downloader] com.skyguy126.soundclouddownloader scd_prefs
07-12 01:04:50.730 I/Xposed  ( 9508): [SoundCloud Downloader] Include metadata: true
07-12 01:04:50.733 I/Xposed  ( 9508): [SoundCloud Downloader] Save location: 1
07-12 01:04:50.736 I/Xposed  ( 9508): [SoundCloud Downloader] Download path: /storage/emulated/0/Download/VSNS - Wild Love.mp3
07-12 01:04:54.653 I/Xposed  ( 9508): [SoundCloud Downloader] Entering album art downloader...
07-12 01:04:54.653 I/Xposed  ( 9508): [SoundCloud Downloader] Unregistered receiver, starting Picasso...
07-12 01:04:54.676 I/Xposed  ( 9508): [SoundCloud Downloader] Preparing to load picasso...


(--- processe ended here without adding metadata to the file
i dont know why the file have just the artiste - track name 
without the metadata  ... but when i remove the downloaded mp3 and redownladed it ... it works ----)


07-12 01:06:34.856 I/Xposed  ( 9508): [SoundCloud Downloader] Entered download catcher...
07-12 01:06:34.856 I/Xposed  ( 9508): [SoundCloud Downloader] Track name: VSNS - Wild Love
07-12 01:06:34.856 I/Xposed  ( 9508): [SoundCloud Downloader] Found genre data...
07-12 01:06:34.856 I/Xposed  ( 9508): [SoundCloud Downloader] Image url: https://i1.sndcdn.com/artworks-000338624265-qig8ss-original.jpg
07-12 01:06:34.863 I/Xposed  ( 9508): [SoundCloud Downloader] com.skyguy126.soundclouddownloader scd_prefs
07-12 01:06:34.863 I/Xposed  ( 9508): [SoundCloud Downloader] Include metadata: true
07-12 01:06:34.863 I/Xposed  ( 9508): [SoundCloud Downloader] Save location: 1
07-12 01:06:34.870 I/Xposed  ( 9508): [SoundCloud Downloader] Download path: /storage/emulated/0/Download/VSNS - Wild Love.mp3
07-12 01:06:34.870 I/Xposed  ( 9508): [SoundCloud Downloader] Adding metadata injector...
07-12 01:06:41.530 I/Xposed  ( 9508): [SoundCloud Downloader] Entering album art downloader...
07-12 01:06:41.530 I/Xposed  ( 9508): [SoundCloud Downloader] Unregistered receiver, starting Picasso...
07-12 01:06:42.156 I/Xposed  ( 9508): [SoundCloud Downloader] Finished writing metadata...
07-12 01:06:42.156 I/Xposed  ( 9508): [SoundCloud Downloader] Broadcasting update to media scanner...
07-12 01:07:49.390 W/Xposed  ( 7946): Package name for /system/csc/appresource/CSCAppResource.apk had to be retrieved via parser

output is correctly work as it should

**Comment by waelchateur** [comment]
i have tryed to modify the bitmap compression ratio to 100%
0% didnt worked for me the artwork looks agly
and i changed "t250/250" by "original" so i can got the original size of the artwok 
it works perfectly

this is the log you demanded :

07-12 01:04:23.246 I/Xposed  ( 9508): [SoundCloud Downloader] Module entry, version 1.5.6
07-12 01:04:23.290 I/Xposed  ( 9508): [SoundCloud Downloader] Initialized
07-12 01:04:31.620 I/Xposed  ( 9508): [SoundCloud Downloader] Entered download catcher...
07-12 01:04:31.626 I/Xposed  ( 9508): [SoundCloud Downloader] Track name: VSNS - Wild Love
07-12 01:04:31.630 I/Xposed  ( 9508): [SoundCloud Downloader] Found genre data...
07-12 01:04:31.630 I/Xposed  ( 9508): [SoundCloud Downloader] Image url: https://i1.sndcdn.com/artworks-000338624265-qig8ss-original.jpg
07-12 01:04:31.640 I/Xposed  ( 9508): [SoundCloud Downloader] com.skyguy126.soundclouddownloader scd_prefs
07-12 01:04:31.643 I/Xposed  ( 9508): [SoundCloud Downloader] Include metadata: true
07-12 01:04:31.643 I/Xposed  ( 9508): [SoundCloud Downloader] Save location: 1
07-12 01:04:31.646 I/Xposed  ( 9508): [SoundCloud Downloader] Download path: /storage/emulated/0/Download/VSNS - Wild Love.mp3
07-12 01:04:31.650 I/Xposed  ( 9508): [SoundCloud Downloader] Adding metadata injector...
07-12 01:04:50.713 I/Xposed  ( 9508): [SoundCloud Downloader] Entered download catcher...
07-12 01:04:50.713 I/Xposed  ( 9508): [SoundCloud Downloader] Track name: VSNS - Wild Love
07-12 01:04:50.713 I/Xposed  ( 9508): [SoundCloud Downloader] Found genre data...
07-12 01:04:50.713 I/Xposed  ( 9508): [SoundCloud Downloader] Image url: https://i1.sndcdn.com/artworks-000338624265-qig8ss-original.jpg
07-12 01:04:50.723 I/Xposed  ( 9508): [SoundCloud Downloader] com.skyguy126.soundclouddownloader scd_prefs
07-12 01:04:50.730 I/Xposed  ( 9508): [SoundCloud Downloader] Include metadata: true
07-12 01:04:50.733 I/Xposed  ( 9508): [SoundCloud Downloader] Save location: 1
07-12 01:04:50.736 I/Xposed  ( 9508): [SoundCloud Downloader] Download path: /storage/emulated/0/Download/VSNS - Wild Love.mp3
07-12 01:04:54.653 I/Xposed  ( 9508): [SoundCloud Downloader] Entering album art downloader...
07-12 01:04:54.653 I/Xposed  ( 9508): [SoundCloud Downloader] Unregistered receiver, starting Picasso...
07-12 01:04:54.676 I/Xposed  ( 9508): [SoundCloud Downloader] Preparing to load picasso...


(--- processe ended here without adding metadata to the file
i dont know why the file have just the artiste - track name 
without the metadata  ... but when i remove the downloaded mp3 and redownladed it ... it works ----)


07-12 01:06:34.856 I/Xposed  ( 9508): [SoundCloud Downloader] Entered download catcher...
07-12 01:06:34.856 I/Xposed  ( 9508): [SoundCloud Downloader] Track name: VSNS - Wild Love
07-12 01:06:34.856 I/Xposed  ( 9508): [SoundCloud Downloader] Found genre data...
07-12 01:06:34.856 I/Xposed  ( 9508): [SoundCloud Downloader] Image url: https://i1.sndcdn.com/artworks-000338624265-qig8ss-original.jpg
07-12 01:06:34.863 I/Xposed  ( 9508): [SoundCloud Downloader] com.skyguy126.soundclouddownloader scd_prefs
07-12 01:06:34.863 I/Xposed  ( 9508): [SoundCloud Downloader] Include metadata: true
07-12 01:06:34.863 I/Xposed  ( 9508): [SoundCloud Downloader] Save location: 1
07-12 01:06:34.870 I/Xposed  ( 9508): [SoundCloud Downloader] Download path: /storage/emulated/0/Download/VSNS - Wild Love.mp3
07-12 01:06:34.870 I/Xposed  ( 9508): [SoundCloud Downloader] Adding metadata injector...
07-12 01:06:41.530 I/Xposed  ( 9508): [SoundCloud Downloader] Entering album art downloader...
07-12 01:06:41.530 I/Xposed  ( 9508): [SoundCloud Downloader] Unregistered receiver, starting Picasso...
07-12 01:06:42.156 I/Xposed  ( 9508): [SoundCloud Downloader] Finished writing metadata...
07-12 01:06:42.156 I/Xposed  ( 9508): [SoundCloud Downloader] Broadcasting update to media scanner...
07-12 01:07:49.390 W/Xposed  ( 7946): Package name for /system/csc/appresource/CSCAppResource.apk had to be retrieved via parser

output is correctly work as it should

**Comment by waelchateur** [comment]
soudcloud version 02072018

**Comment by skyguy126** [comment]
yeah sometimes picasso fails to load, no idea why. might be a minor networking issue or something. The problem is fixed then?

**Comment by waelchateur** [comment]
artwork quality yes but still sometimes the output mp3 file without any metadata

**Comment by skyguy126** [comment]
if the module cant find genre **AND** artist name **AND** album art it wont add any metadata. Only when it finds all 3 will it add metadata. When doing so sometimes it fails due to a picasso error, I'm not 100% sure why it happens either.

**Comment by waelchateur** [comment]
but this is not the situation as you can see in the log all the needed info are existed genre, name and artwork in both try
but it fail on the  first one and succeded in the second
the problem is that picasso sudenly stoped and the rest of the processe stopped rather than that the developper of picasso said that picasso will retry 3 times if he fail will show an error at the end
the log didnt show any of this 😩
by your opinion it could be caused by the network 🤔 
sorry its not the network i changed to 4g but the same

**Comment by skyguy126** [comment]
I'll make a note to log the error in the next version

**Comment by waelchateur** [comment]
@skyguy126 thank you for your efforts 
i really wich to help but this situation is out of my knowledge
anyway if this will not be fixed since this is a picasso bug
dont worry bro your module still unique and its the best of its kinde 
thank you :+1:

**Comment by skyguy126** [comment]
Updated SCD with db356f9bf65dc7b7194a79374edf5bda6bb786c3. Enabled Picasso logs. Please re-open this issue if you are still having issues.
