### ISSUE TITLE
Error: fgb(bmw,cer)#exact 

### ISSUE THREAD

**Issue by neosurat** [skyguy126/Xposed-SoundCloudDownloader#27]
I have installed SD module 1.5.6 on Xposed version 89 on MIUI 9 Stable rom. And it is giving "Error: fgb(bmw,cer)#exact " in Xposed log. Can anyone give solution ?

**Comment by QuickOK** [comment]
I believe the hooks haven't been updated for the current version of SoundCloud. You'll need to download an older version of SoundCloud for it to work.

**Comment by QuickOK** [comment]
@neosurat use apkmirror 2018.07.02 or 2018.07.12 should work

**Comment by skyguy126** [comment]
fixed with db356f9bf65dc7b7194a79374edf5bda6bb786c3.
