### ISSUE TITLE
Dont download

### ISSUE THREAD

**Issue by feeduart** [skyguy126/Xposed-SoundCloudDownloader#3]
When i did the download appear the message: write access denied, grant e retry!

Mobile: Lenovo Vibe A7010/ K4 note
Root: OK
OS: LineageOS 13

**Comment by skyguy126** [comment]
@feeduart This error means that the app (Soundcloud not the Xposed module) doesn't have permission to write to your phone's external storage. Usually you can enable it through Privacy Guard (found in settings) and if you hold down the app icon and drag it to `App info`, then click permissions. Make sure the Storage option is turned on.

I will try and make the error more descriptive in the next update.

**Comment by feeduart** [comment]
Thank you very much.
