### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by wallacescott1** [skyguy126/Xposed-SoundCloudDownloader#30]
First of all thanks for the mod, 2nd is that i'm facing a problem, the download options is not appearing at all, i am using a S7 Edge with oreo, Xposed module in MagiskSU in the latest released version. The SoundCloud app is in version 2018.10.09-release but i tried 2018.07.30 version as well, the module is at the latest version and i did tried one update back too. Hope u are still working in this great mod, and maybe help me fix it. 

Thanks for your time.

**Comment by wallacescott1** [comment]
Forgot to say that i did deactivated all the other Xposed modules too but to no avail.

**Comment by juppin** [comment]
You need the version 2018.09.25 of SoundCloud as the hooks only work for this specific version because all classes are obfuscated and thats why every build has other method names.

https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/soundcloud-soundcloud-2018-09-25-release-release/

**Comment by wallacescott1** [comment]
Great, i noticed that, in update description it says "updated Hooks for release xxxxx" i downloaded the correct version, now it's working perfectly, thanks dude.
