### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by KaMyKaSii** [skyguy126/Xposed-SoundCloudDownloader#4]
Any possibility to do some similar module for Spotify?

**Comment by skyguy126** [comment]
@KaMyKaSii I personally don't use Spotify so I'm not too sure. Really depends if the source code isn't too obfuscated and if they have checks against downloading it like that.

**Comment by KaMyKaSii** [comment]
@skyguy126 I think downloading is impossible, they should have great protection against this. But the files are cached in the device, but encrypted. Would a module be able to capture audio from Spotify's memory after being decrypted and reproduced?
![screenshot_20170329-230206](https://cloud.githubusercontent.com/assets/17092335/24484297/d8493438-14d3-11e7-97e6-9d2f22ee3a91.png)

**Comment by skyguy126** [comment]
@KaMyKaSii Not 100% sure will have to take a look at the source code first. That being said I'm sure its 100% possible to implement, the question is if it is viable to do it a certain way or not. Looking at sources right now will get back to you.

**Comment by KaMyKaSii** [comment]
@skyguy126 All right, thank you very much! Please inform me of any news

**Comment by skyguy126** [comment]
@KaMyKaSii Code seems pretty heavily obfuscated unfortunately

**Comment by KaMyKaSii** [comment]
@skyguy126 Did you look at the source code? Decompiling apk in Java code does not help in anything?

**Comment by skyguy126** [comment]
@KaMyKaSii I did decompile the apk, you can view it yourself if you'd like. Pull the apk from your phone to your computer. Extract `classes.dex` from the apk using 7zip or any other program. Run it through `dex2jar` and view the output jar file in `jdgui` or any other decompilation program.

**Comment by KaMyKaSii** [comment]
@skyguy126 use a module like InstallerOpt to make all applications debuggable and capture a logcat while running a song in Spotify can help in something?

**Comment by skyguy126** [comment]
@KaMyKaSii good point, will do

**Comment by KaMyKaSii** [comment]
@skyguy126 unsuccessfully?

**Comment by skyguy126** [comment]
@KaMyKaSii I closed the issue because it does not directly pertain to this module but we can still discuss here in comments. EDIT: also found a few methods that might allow this, will have to test later though.

**Comment by KaMyKaSii** [comment]
@skyguy126 I'm very happy to hear this. Let me know if you need a tester or anything.

**Comment by skyguy126** [comment]
@KaMyKaSii Some news: Found the methods that control the player and successfully hooked them. Still not sure if I am going in the right direction but the next step is to find and extract the track being played (which I think is very possible but again no guarantees).

**Comment by KaMyKaSii** [comment]
@skyguy126 Wow! Good job! I hope you succeed, it will be a very appreciated module

**Comment by KaMyKaSii** [comment]
Hello @skyguy126 not wanting to rush you or something, but some news or progress?

**Comment by bonebizz21** [comment]
I need help getting my songs back from Spotify o. Too as card

**Comment by skyguy126** [comment]
@bonebizz21 Off topic. No relation to this module.
