### ISSUE TITLE
Not working? Little help. 

### ISSUE THREAD

**Issue by Hongsmind** [skyguy126/Xposed-SoundCloudDownloader#6]
"Write access denied, grant and retry"
After I press download that's what error pops up

**Comment by alizreik-au** [comment]
Hongsmind, did you resolve the issue?
Because I can't seem to get it working.

**Comment by alizreik-au** [comment]
Never mind, I found the solution in a previous post:
https://github.com/skyguy126/Xposed-SoundCloudDownloader/issues/3
