### ISSUE TITLE
Won't download

### ISSUE THREAD

**Issue by wishyu** [skyguy126/Xposed-SoundCloudDownloader#8]
When pressing the download, nothing happens.
Here's the xposed log
Oct 4, 2017 1:50:51 PM UTC
Loading Xposed v54 (for Zygote)...
Running ROM '16.0.B.2.16' with fingerprint 'Sony/C2305/C2305:4.2.2/16.0.B.2.16/eng.administrator.1403963097:user/release-keys'
Loading modules from /data/app/com.skyguy126.soundclouddownloader-1.apk
  Loading class com.skyguy126.soundclouddownloader.XposedMod
[SoundCloud Downloader] Entry
[SoundCloud Downloader] Error: java.lang.ClassNotFoundException: com.soundcloud.android.model.Urn

**Comment by skyguy126** [comment]
Looks like there has been a sound-cloud update, I will look into the new hooks soon.

**Comment by skyguy126** [comment]
Nevermind, download seems to be working fine for me. Are you sure you are using the latest version of scd?

**Comment by wishyu** [comment]
Using scd version 1.2
And SoundCloud version 2017.09.14-release

**Comment by skyguy126** [comment]
Not too sure why this is happening, I am also on the same versions and my download option works fine. From which menu are you pressing download, as in the track page, or from the liked tracks list view, or where exactly?

**Comment by wishyu** [comment]
Using the Now Playing

**Comment by skyguy126** [comment]
What android version are you on?

**Comment by wishyu** [comment]
Android Jelly bean 4.2.2

**Comment by skyguy126** [comment]
I am not sure if the SoundCloud app has a different model for playing songs on jelly bean and I will have to look into that. Not too sure what can be done.

**Comment by mistrparas** [comment]
nothing works by clicking download button....why....???
sound cloud app version - 2017.11.14
scd version- 1.2
device - yureka plus (yu5510a)
android- 4.4.4

**Comment by skyguy126** [comment]
@mistrparas Soundcloud seems to operate in a different format for older Android versions, I don't have a way to test and fix the issue as none of my devices are running android 4.
