### ISSUE TITLE
Not working after latest update 1.3 [GS8]

### ISSUE THREAD

**Issue by fortifiedSteelBoot** [skyguy126/Xposed-SoundCloudDownloader#9]
Hello im on Galaxy S8 running Xposed 88.2, previous version of this worked fine downloaded perfectly once I updated the option to Download still appeared but when I go to press it nothing happens already tryed reinstalling.

**Comment by skyguy126** [comment]
@fortifiedSteelBoot can you post your xposed log here after running soundcloud.

**Comment by hivinau** [comment]
Hello, same issue for me. I'm on Android 4.3. 
The xposed log according to your app :
SoundCloud Downloader] Entry
[SoundCloud Downloader] Error: com.soundcloud.android.tracks.TrackItemMenuPresenter#createAndShowMenu(android.view.View)#exact

**Comment by skyguy126** [comment]
@hivinau What version is your Soundcloud app. 1.3 is for version 2017.12.14.

**Comment by hivinau** [comment]
Oh, good. I'm using version 2017.11.30-release. I'll update on version you specify and keep you posted

**Comment by skyguy126** [comment]
@hivinau thank you!

**Comment by hivinau** [comment]
I test on version 2017.12.14-beta, it's actually working great ! Thank you !

**Comment by fortifiedSteelBoot** [comment]
My apoligies, did not know I was supposed to be on 2017.12.14 , im now running it perfectly fine thanks.

**Comment by skyguy126** [comment]
@fortifiedSteelBoot No worries! I should have indicated the version number in the release notes.
